#!/usr/bin/env python3
"""Generate the explicitly non-public Chapter 20 release-candidate fixture."""
from __future__ import annotations
import csv,hashlib
from pathlib import Path
import yaml
ROOT=Path(__file__).resolve().parents[2];DATA_ROOT=ROOT/"companion"/"data";CHAPTER_ROOT=DATA_ROOT/"ch20"/"release_candidate";STATUS="SYNTHETIC_TEACHING_FIXTURE"
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write_tsv(p,rows,fields):
 p.parent.mkdir(parents=True,exist_ok=True)
 with p.open("w",encoding="utf-8",newline="") as t:w=csv.DictWriter(t,fieldnames=fields,delimiter="\t",extrasaction="ignore");w.writeheader();w.writerows(rows)
def main():
 CHAPTER_ROOT.mkdir(parents=True,exist_ok=True)
 sources=[("COMPANION_NOTICE","companion/NOTICE.md","documentation","text/markdown"),("COMPANION_CITATION","companion/CITATION.cff","citation","text/yaml"),("CODE_LICENSE","companion/LICENSE","license","text/plain"),("DATA_LICENSE","companion/LICENSE-DATA.txt","license","text/plain"),("COMPANION_README","companion/README.md","documentation","text/markdown"),("PYTHON_REQUIREMENTS","companion/requirements-python.txt","environment","text/plain"),("R_REQUIREMENTS","companion/requirements-r.txt","environment","text/plain"),("CH19_NOTEBOOK_1","companion/notebooks/ch19/01_results_uncertainty_and_equivalence.ipynb","notebook","application/x-ipynb+json"),("CH19_NOTEBOOK_2","companion/notebooks/ch19/02_claim_evidence_map.ipynb","notebook","application/x-ipynb+json")]
 rows=[]
 for aid,rel,role,media in sources:
  p=ROOT/rel
  if not p.exists():raise FileNotFoundError(p)
  rows.append({"artifact_id":aid,"path":rel,"role":role,"media_type":media,"access_class":"candidate_internal","rights_holder":"AUTHOR_INPUT_REQUIRED","license_or_agreement":"UNLICENSED_PENDING_PUBLISHER_APPROVAL","redistributable":"false","source_or_generator":"companion package file","version":"candidate-0.1.0","sha256":sha(p),"citation_id":"AUTHOR_INPUT_REQUIRED","contains_personal_data":"false","contains_restricted_content":"false","release_disposition":"internal_candidate_only","provenance_id":"CH20_ALLOWLIST"})
 write_tsv(CHAPTER_ROOT/"release_manifest.tsv",rows,list(rows[0]))
 license_rows=[{"component":"all allowlisted book and companion files","rights_holder":"AUTHOR_INPUT_REQUIRED","license_or_agreement":"UNLICENSED_PENDING_PUBLISHER_APPROVAL","redistribution_status":"not_authorized","modification_permission":"unresolved","attribution":"AUTHOR_INPUT_REQUIRED","restriction":"publisher repository and licensing policy unresolved","decision":"fail_public_release","data_status":STATUS},{"component":"synthetic teaching fixtures","rights_holder":"AUTHOR_INPUT_REQUIRED","license_or_agreement":"UNLICENSED_INTERNAL_PENDING_PUBLISHER_APPROVAL","redistribution_status":"not_authorized","modification_permission":"unresolved","attribution":"AUTHOR_INPUT_REQUIRED","restriction":"must not be relabeled as participant observations","decision":"fail_public_release","data_status":STATUS}]
 write_tsv(CHAPTER_ROOT/"license_matrix.tsv",license_rows,list(license_rows[0]))
 governance=[{"review_id":"GOV_AUTHOR","review_domain":"author identity and authority","reviewer_or_authority":"AUTHOR_INPUT_REQUIRED","decision":"pending","decision_date":"","record_status":"UNSIGNED_PLACEHOLDER","public_release_authorized":"false","data_status":STATUS},{"review_id":"GOV_PUBLISHER","review_domain":"external repository and license policy","reviewer_or_authority":"PUBLISHER_INPUT_REQUIRED","decision":"pending","decision_date":"","record_status":"UNSIGNED_PLACEHOLDER","public_release_authorized":"false","data_status":STATUS},{"review_id":"GOV_PRIVACY","review_domain":"automated candidate privacy scan","reviewer_or_authority":"workflow","decision":"run_not_human_approval","decision_date":"","record_status":"AUTOMATED_ONLY","public_release_authorized":"false","data_status":STATUS}]
 write_tsv(CHAPTER_ROOT/"governance_decisions.tsv",governance,list(governance[0]))
 spec={"schema_version":"1.0","data_status":STATUS,"release":{"project_id":"PHONETIC_RESEARCH_IN_PRACTICE","release_version":"candidate-0.1.0","release_date":"AUTHOR_INPUT_REQUIRED","supported_manuscript_or_edition":"first substantive English draft","status":"internal_candidate","allowlist_only":True},"routes":{"protected":{"profile":"protected_profile.yaml","public":False},"public":{"profile":"public_profile.yaml","public":False,"reason":"authorization and license gates remain open"},"shared_transformation_code":True},"governance":{"human_review_required":True,"unresolved_permission_defaults_to_restricted":True},"build":{"clean_candidate_directory":True,"unexpected_file_policy":"fail","checksum_algorithm":"sha256"},"audits":{"identifiers":True,"secrets":True,"private_paths":True,"unapproved_media":True,"notebook_outputs":True,"license_compatibility":True,"human_governance_review":True},"archive":{"provider":"AUTHOR_AND_PUBLISHER_INPUT_REQUIRED","version_specific_identifier":"AUTHOR_INPUT_REQUIRED_UNTIL_AUTHORIZED_DEPOSIT","concept_identifier":"AUTHOR_INPUT_REQUIRED_UNTIL_AUTHORIZED_DEPOSIT","deposit_authorized":False,"publish_authorized":False}}
 (CHAPTER_ROOT/"release_spec.yaml").write_text(yaml.safe_dump(spec,sort_keys=False),encoding="utf-8")
 for name,payload in {"public_profile.yaml":{"data_status":STATUS,"route":"public_candidate","public_execution_permitted":True,"public_deposit_authorized":False,"inputs":"allowlisted repository files only","protected_data":False},"protected_profile.yaml":{"data_status":"CONFIGURATION_ONLY_NO_DATA","route":"protected","canonical_input":"AUTHORIZED_LOCAL_PATH_REQUIRED","public":False,"execute_in_public_notebook":False}}.items():(CHAPTER_ROOT/name).write_text(yaml.safe_dump(payload,sort_keys=False),encoding="utf-8")
 citation={"data_status":STATUS,"title":"Phonetic Research in Practice companion candidate","authors":"AUTHOR_INPUT_REQUIRED","version":"candidate-0.1.0","preferred_citation":"AUTHOR_AND_PUBLISHER_INPUT_REQUIRED","version_specific_identifier":"NOT_CREATED","concept_identifier":"NOT_CREATED","deposit_status":"NOT_DEPOSITED"};(CHAPTER_ROOT/"citation_metadata.yaml").write_text(yaml.safe_dump(citation,sort_keys=False),encoding="utf-8")
 (CHAPTER_ROOT/"availability_statement_template.md").write_text("# Availability statement\n\nThis is an internal release candidate. No public deposit or DOI has been created. Public materials and licenses remain subject to author and publisher approval. The candidate contains only allowlisted documentation, environment records, and synthetic-workflow notebooks; it contains no participant recordings or transcripts. Protected and licensed source data are not redistributed.\n",encoding="utf-8")
 (CHAPTER_ROOT/"maintenance_policy.md").write_text("# Maintenance and withdrawal policy\n\nTagged archival versions, if authorized, will remain distinct from the maintained repository. Corrections create a new version and state whether code, numerical outputs, or scientific conclusions changed. Critical privacy, rights, or governance incidents trigger access restriction and documented review. Withdrawal authority, contact, duration, repository, and publisher procedures remain author- and publisher-controlled fields before release.\n",encoding="utf-8")
 files=sorted(p for p in CHAPTER_ROOT.iterdir() if p.is_file());generated=[]
 for i,p in enumerate(files):generated.append({"artifact_id":f"CH20_SYN_{i+1:02d}","relative_path":str(p.relative_to(DATA_ROOT)),"data_status":"CONFIGURATION_ONLY_NO_DATA" if p.name=="protected_profile.yaml" else STATUS,"source":"generated locally by companion/scripts/generate_ch20_fixture.py","license":"CC-BY-4.0","sha256":sha(p),"contains_human_data":"false"})
 manifest=DATA_ROOT/"MANIFEST.tsv";preserved=[]
 if manifest.exists():
  with manifest.open(encoding="utf-8",newline="") as s:preserved=[r for r in csv.DictReader(s,delimiter="\t") if not r["artifact_id"].startswith("CH20_")]
 write_tsv(manifest,sorted(preserved+generated,key=lambda x:x["artifact_id"]),["artifact_id","relative_path","data_status","source","license","sha256","contains_human_data"])
if __name__=="__main__":main()
