required_packages_ch18<-c("digest","jsonlite","mgcv","yaml");missing_packages_ch18<-required_packages_ch18[!vapply(required_packages_ch18,requireNamespace,logical(1),quietly=TRUE)];if(length(missing_packages_ch18))stop("Missing R packages: ",paste(missing_packages_ch18,collapse=", "))
STATUS_CH18<-"SYNTHETIC_TEACHING_FIXTURE"
read_tsv_ch18<-function(path)utils::read.delim(path,sep="\t",quote="",stringsAsFactors=FALSE,check.names=FALSE)
write_tsv_ch18<-function(x,path){dir.create(dirname(path),recursive=TRUE,showWarnings=FALSE);utils::write.table(x,path,sep="\t",quote=FALSE,row.names=FALSE,na="")}
sha256_ch18<-function(path)digest::digest(file=path,algo="sha256",serialize=FALSE)
write_provenance_ch18<-function(path,tool,inputs,decisions)jsonlite::write_json(list(tool=tool,tool_version="0.1.0",r_version=R.version.string,run_at_utc=format(Sys.time(),tz="UTC",usetz=TRUE),input_hashes=stats::setNames(lapply(inputs,sha256_ch18),normalizePath(inputs)),decisions=decisions),path,pretty=TRUE,auto_unbox=TRUE)
html_table_ch18<-function(x){e<-function(z){z<-gsub("&","&amp;",as.character(z),fixed=TRUE);z<-gsub("<","&lt;",z,fixed=TRUE);gsub(">","&gt;",z,fixed=TRUE)};paste0("<table border='1'><thead><tr>",paste0("<th>",e(names(x)),"</th>",collapse=""),"</tr></thead><tbody>",paste(apply(x,1,function(r)paste0("<tr>",paste0("<td>",e(r),"</td>",collapse=""),"</tr>")),collapse=""),"</tbody></table>")}
lag1_ch18<-function(x,g){parts<-split(x,g);values<-vapply(parts,function(z)if(length(z)>2)stats::cor(z[-length(z)],z[-1],use="complete.obs") else NA_real_,numeric(1));mean(values[is.finite(values)])}
run_dynamic_error_missingness<-function(frames_path,boundaries_path,validation_path,codes_path,error_path,spec_path,ch14_spec_path,output_dir){
 frames<-read_tsv_ch18(frames_path);bounds<-read_tsv_ch18(boundaries_path);validation<-read_tsv_ch18(validation_path);codes<-read_tsv_ch18(codes_path);scenarios<-read_tsv_ch18(error_path);spec<-yaml::read_yaml(spec_path);ch14<-yaml::read_yaml(ch14_spec_path)
 if(!all(c(frames$data_status,bounds$data_status,validation$data_status,codes$data_status,scenarios$data_status,spec$data_status)==STATUS_CH18))stop("Chapter 18 inputs must remain explicitly synthetic")
 frames$measured_value<-as.numeric(frames$measured_value);frames$true_value<-as.numeric(frames$true_value);frames$time_normalized<-as.numeric(frames$time_normalized);frames$condition<-factor(frames$condition);frames$speaker_id<-factor(frames$speaker_id);frames$item_id<-factor(frames$item_id)
 observed<-frames[frames$availability_code=="observed" & is.finite(frames$measured_value),]
 midpoint<-observed[abs(observed$time_normalized-.5)<1e-8,];benchmark<-stats::lm(measured_value~condition,data=midpoint)
 dynamic<-mgcv::gam(measured_value~condition+s(time_normalized,k=7,bs="cs")+s(time_normalized,by=condition,k=7,bs="cs")+s(speaker_id,bs="re")+s(item_id,bs="re"),data=observed,method="REML")
 dynamic_resid<-stats::residuals(dynamic);linear<-stats::lm(measured_value~condition+time_normalized+speaker_id+item_id,data=observed);linear_resid<-stats::residuals(linear)
 residual_dependence<-data.frame(model_id=c("linear_trajectory_benchmark","dynamic_gam"),mean_within_token_lag1=c(lag1_ch18(linear_resid,observed$token_id),lag1_ch18(dynamic_resid,observed$token_id)),independent_replication_unit="token_id",frame_count_is_replication_count=FALSE,data_status=STATUS_CH18)
 support<-stats::aggregate(frame_id~condition+time_normalized,observed,length);names(support)[3]<-"observed_frames";tokens<-stats::aggregate(token_id~condition+time_normalized,observed,function(x)length(unique(x)));names(tokens)[3]<-"contributing_tokens";support<-merge(support,tokens,by=c("condition","time_normalized"));support$data_status<-STATUS_CH18
 missing<-merge(frames,codes,by="availability_code",all.x=TRUE);missing_map<-stats::aggregate(frame_id~availability_code+condition+observation_process+imputation_permitted,missing,length);names(missing_map)[5]<-"frames";missing_map$proportion<-missing_map$frames/nrow(frames);missing_map$structural_absence_imputed<-FALSE;missing_map$data_status<-STATUS_CH18
 validation_error<-as.numeric(validation$measured_value)-as.numeric(validation$reference_value);error_sd<-stats::sd(validation_error);set.seed(as.integer(spec$seed));base_coef<-stats::coef(benchmark)[["conditionB"]];results<-list();j<-0
 for(i in 1:30){j<-j+1;y<-midpoint$measured_value+stats::rnorm(nrow(midpoint),0,error_sd);results[[j]]<-data.frame(scenario_id="validation_random",replicate=i,estimate=stats::coef(stats::lm(y~midpoint$condition))[[2]],primary_estimate=base_coef,error_scale=error_sd,evidence_status="validation_derived_fixture",seed=as.integer(spec$seed),data_status=STATUS_CH18)}
 set.seed(as.integer(spec$seed)+1);for(i in 1:30){j<-j+1;bias<-stats::runif(1,0,2);y<-midpoint$measured_value+ifelse(midpoint$condition=="B",bias,0);results[[j]]<-data.frame(scenario_id="hypothetical_differential",replicate=i,estimate=stats::coef(stats::lm(y~midpoint$condition))[[2]],primary_estimate=base_coef,error_scale=bias,evidence_status="HYPOTHETICAL_SENSITIVITY_ONLY",seed=as.integer(spec$seed)+1,data_status=STATUS_CH18)}
 measurement<-do.call(rbind,results);dir.create(output_dir,recursive=TRUE,showWarnings=FALSE);saveRDS(benchmark,file.path(output_dir,"benchmark_model.rds"));saveRDS(dynamic,file.path(output_dir,"dynamic_model.rds"));write_tsv_ch18(support,file.path(output_dir,"trajectory_support.tsv"));write_tsv_ch18(residual_dependence,file.path(output_dir,"residual_dependence.tsv"));write_tsv_ch18(measurement,file.path(output_dir,"measurement_error_results.tsv"));write_tsv_ch18(missing_map,file.path(output_dir,"missingness_map.tsv"))
 report<-paste0("<!doctype html><meta charset='utf-8'><title>Missingness and imputation diagnostics</title><h1>Observation-process audit</h1><p><strong>Data status:</strong> SYNTHETIC_TEACHING_FIXTURE. Imputation is disabled. Structural absence and censoring are never replaced by acoustic values.</p>",html_table_ch18(missing_map));writeLines(report,file.path(output_dir,"imputation_diagnostics.html"),useBytes=TRUE)
 decisions<-list(dynamic_required_for_generated_shape=TRUE,frame_count_is_replication_count=FALSE,measurement_validation_sd=error_sd,hypothetical_scenario_labeled=TRUE,imputation_performed=FALSE,structural_absence_imputed=FALSE,chapter14_schema_version=ch14$schema_version,interpretive_limit="workflow and estimator test only")
 write_provenance_ch18(file.path(output_dir,"run_provenance.json"),"run_dynamic_error_missingness",c(frames_path,boundaries_path,validation_path,codes_path,error_path,spec_path,ch14_spec_path),decisions);list(support=support,residual_dependence=residual_dependence,measurement=measurement,missingness=missing_map,decisions=decisions)
}
assign_folds_ch18<-function(data,policy){set.seed(as.integer(policy$seed));row_fold<-sample(rep(1:5,length.out=nrow(data)));unit_fold<-function(x,k){u<-unique(x);set.seed(as.integer(policy$seed)+k);m<-stats::setNames(sample(rep(1:k,length.out=length(u))),u);unname(m[x])};data.frame(observation_id=data$observation_id,row_random=row_fold,speaker_heldout=unit_fold(data$speaker_id,5),item_heldout=unit_fold(data$item_id,4),session_heldout=unit_fold(data$session_id,2),corpus_heldout=unit_fold(data$corpus_id,2),data_status=STATUS_CH18)}
calibration_ch18<-function(y,p){p<-pmin(pmax(p,1e-6),1-1e-6);fit<-stats::glm(y~stats::qlogis(p),family=stats::binomial());c(intercept=stats::coef(fit)[1],slope=stats::coef(fit)[2])}
run_prediction_validation_scope<-function(feature_path,candidates_path,policy_path,domain_path,recipe_path,outcome_path,claim_path,dynamic_output_dir,output_dir){
 data<-read_tsv_ch18(feature_path);candidates<-read_tsv_ch18(candidates_path);policy<-yaml::read_yaml(policy_path);domain<-yaml::read_yaml(domain_path);recipe<-yaml::read_yaml(recipe_path);outcome<-yaml::read_yaml(outcome_path);claim<-yaml::read_yaml(claim_path)
 if(!all(c(data$data_status,candidates$data_status,policy$data_status,domain$data_status,recipe$data_status,outcome$data_status,claim$data_status)==STATUS_CH18))stop("Chapter 18 prediction inputs must remain explicitly synthetic")
 features<-c("cue_1","cue_2","speaker_signature","device_signature");for(x in features)data[[x]]<-as.numeric(data[[x]]);data$outcome<-as.integer(data$outcome);folds<-assign_folds_ch18(data,policy);merged<-merge(data,folds,by="observation_id");schemes=c("row_random","speaker_heldout","item_heldout","session_heldout","corpus_heldout");unit_map=c(row_random="row",speaker_heldout="speaker_id",item_heldout="item_id",session_heldout="session_id",corpus_heldout="corpus_id")
 performance<-list();calibration<-list();domain_errors<-list();audit<-list();pred_index<-0
 for(scheme in schemes){fold_values<-sort(unique(merged[[scheme]]));for(fold in fold_values){test<-merged[merged[[scheme]]==fold,];train<-merged[merged[[scheme]]!=fold,];target<-unit_map[[scheme]];overlap<-function(field)length(intersect(unique(train[[field]]),unique(test[[field]])));audit[[length(audit)+1]]<-data.frame(scheme=scheme,fold=fold,target_unit=target,speaker_overlap=overlap("speaker_id"),item_overlap=overlap("item_id"),session_overlap=overlap("session_id"),corpus_overlap=overlap("corpus_id"),target_leakage=ifelse(target=="row",NA,overlap(target)>0),preprocessing_fit_on_training_only=TRUE,data_status=STATUS_CH18)
  for(i in seq_len(nrow(candidates))){model_id<-candidates$model_id[[i]];used<-if(model_id=="cue_only")c("cue_1","cue_2") else features;means<-vapply(train[used],mean,numeric(1));sds<-vapply(train[used],stats::sd,numeric(1));sds[sds==0]<-1;tr<-train;te<-test;for(x in used){tr[[x]]<-(tr[[x]]-means[[x]])/sds[[x]];te[[x]]<-(te[[x]]-means[[x]])/sds[[x]]};formula<-stats::as.formula(paste("outcome ~",paste(used,collapse=" + ")));fit<-stats::glm(formula,data=tr,family=stats::binomial());p<-stats::predict(fit,newdata=te,type="response");pred<-as.integer(p>=.5);cal<-calibration_ch18(te$outcome,p);pred_index<-pred_index+1;performance[[pred_index]]<-data.frame(scheme=scheme,fold=fold,model_id=model_id,test_rows=nrow(te),deployment_units=if(target=="row")nrow(te) else length(unique(te[[target]])),accuracy=mean(pred==te$outcome),brier=mean((p-te$outcome)^2),data_status=STATUS_CH18);calibration[[pred_index]]<-data.frame(scheme=scheme,fold=fold,model_id=model_id,calibration_intercept=unname(cal[1]),calibration_slope=unname(cal[2]),mean_predicted=mean(p),observed_prevalence=mean(te$outcome),data_status=STATUS_CH18)
   for(corpus in unique(te$corpus_id)){keep<-te$corpus_id==corpus;domain_errors[[length(domain_errors)+1]]<-data.frame(scheme=scheme,fold=fold,model_id=model_id,domain_type="corpus",domain=corpus,n=sum(keep),accuracy=mean(pred[keep]==te$outcome[keep]),brier=mean((p[keep]-te$outcome[keep])^2),data_status=STATUS_CH18)}
  }} }
 performance<-do.call(rbind,performance);calibration<-do.call(rbind,calibration);domain_errors<-do.call(rbind,domain_errors);audit<-do.call(rbind,audit);comparison<-stats::aggregate(cbind(accuracy,brier)~scheme+model_id,performance,function(x)c(mean=mean(x),sd=stats::sd(x)));comparison<-data.frame(scheme=comparison$scheme,model_id=comparison$model_id,accuracy_mean=comparison$accuracy[,"mean"],accuracy_fold_sd=comparison$accuracy[,"sd"],brier_mean=comparison$brier[,"mean"],brier_fold_sd=comparison$brier[,"sd"],selection_rule="new-speaker performance is primary; no significance voting",data_status=STATUS_CH18)
 dynamic_files<-c("residual_dependence.tsv","measurement_error_results.tsv","missingness_map.tsv");if(!all(file.exists(file.path(dynamic_output_dir,dynamic_files))))stop("Run Chapter 18 notebook 1 first")
 primary<-comparison[comparison$scheme=="speaker_heldout",];best<-primary$model_id[[which.min(primary$brier_mean)]];gate<-list(data_status=STATUS_CH18,decision="restrict",selected_predictive_model=best,population_scope="new synthetic speakers within represented items, sessions, corpora, and generator",measurement_scope="generated cues and declared complete token-level feature process only",predictor_scope="training-fold scaling and observed feature ranges; no extrapolated corpus",goal_scope="prediction only; not causal or mechanistic explanation",row_random_is_new_speaker_evidence=FALSE,preprocessing_inside_folds=all(audit$preprocessing_fit_on_training_only),target_unit_leakage_detected=any(audit$target_leakage,na.rm=TRUE),external_corpus_validation=FALSE,predictive_success_implies_causation=FALSE,linked_dynamic_evidence=dynamic_files)
 dir.create(output_dir,recursive=TRUE,showWarnings=FALSE);write_tsv_ch18(folds,file.path(output_dir,"fold_assignments.tsv"));write_tsv_ch18(audit,file.path(output_dir,"leakage_audit.tsv"));write_tsv_ch18(performance,file.path(output_dir,"validation_performance.tsv"));write_tsv_ch18(calibration,file.path(output_dir,"calibration.tsv"));write_tsv_ch18(domain_errors,file.path(output_dir,"domain_errors.tsv"));write_tsv_ch18(comparison,file.path(output_dir,"model_comparison.tsv"));yaml::write_yaml(gate,file.path(output_dir,"model_scope_gate.yaml"));decisions<-list(primary_validation="speaker_heldout",selected_model=best,fold_rows=nrow(folds),validation_rows=nrow(performance),all_preprocessing_inside_folds=all(audit$preprocessing_fit_on_training_only),target_unit_leakage_detected=any(audit$target_leakage,na.rm=TRUE),decision=gate$decision)
 write_provenance_ch18(file.path(output_dir,"run_provenance.json"),"run_prediction_validation_scope",c(feature_path,candidates_path,policy_path,domain_path,recipe_path,outcome_path,claim_path,file.path(dynamic_output_dir,dynamic_files)),decisions);list(folds=folds,audit=audit,performance=performance,calibration=calibration,domain_errors=domain_errors,comparison=comparison,gate=gate,decisions=decisions)
}
