required_packages_ch19<-c("digest","jsonlite","yaml");missing_packages_ch19<-required_packages_ch19[!vapply(required_packages_ch19,requireNamespace,logical(1),quietly=TRUE)];if(length(missing_packages_ch19))stop("Missing R packages: ",paste(missing_packages_ch19,collapse=", "))
STATUS_CH19<-"SYNTHETIC_TEACHING_FIXTURE";read_tsv_ch19<-function(p)utils::read.delim(p,sep="\t",quote="",stringsAsFactors=FALSE,check.names=FALSE);write_tsv_ch19<-function(x,p){dir.create(dirname(p),recursive=TRUE,showWarnings=FALSE);utils::write.table(x,p,sep="\t",quote=FALSE,row.names=FALSE,na="")};sha256_ch19<-function(p)digest::digest(file=p,algo="sha256",serialize=FALSE);write_provenance_ch19<-function(p,t,inputs,d)jsonlite::write_json(list(tool=t,tool_version="0.1.0",r_version=R.version.string,run_at_utc=format(Sys.time(),tz="UTC",usetz=TRUE),input_hashes=stats::setNames(lapply(inputs,sha256_ch19),normalizePath(inputs)),decisions=d),p,pretty=TRUE,auto_unbox=TRUE)
html_table_ch19<-function(x){e<-function(z){z<-gsub("&","&amp;",as.character(z),fixed=TRUE);z<-gsub("<","&lt;",z,fixed=TRUE);gsub(">","&gt;",z,fixed=TRUE)};paste0("<table border='1'><thead><tr>",paste0("<th>",e(names(x)),"</th>",collapse=""),"</tr></thead><tbody>",paste(apply(x,1,function(r)paste0("<tr>",paste0("<td>",e(r),"</td>",collapse=""),"</tr>")),collapse=""),"</tbody></table>")}
run_results_uncertainty<-function(results_path,scope_gate_path,map_path,bounds_path,scenario_path,sensitivity_path,output_dir){
 results<-read_tsv_ch19(results_path);scope<-yaml::read_yaml(scope_gate_path);map<-yaml::read_yaml(map_path);bounds<-read_tsv_ch19(bounds_path);scenarios<-read_tsv_ch19(scenario_path);sensitivity<-yaml::read_yaml(sensitivity_path)
 if(!all(c(results$data_status,bounds$data_status,scenarios$data_status,scope$data_status,map$data_status,sensitivity$data_status)==STATUS_CH19))stop("Chapter 19 inputs must remain explicitly synthetic")
 joined<-merge(results,bounds,by="contrast_id",all.x=TRUE);joined$direction<-ifelse(joined$estimate>0,"positive",ifelse(joined$estimate<0,"negative","zero"));joined$precision_width<-joined$ci_high-joined$ci_low;joined$meaningful_bound_source_status<-joined$source_status;joined$threshold_verdict_used<-FALSE;joined$data_status<-STATUS_CH19
 equivalence<-joined[,c("contrast_id","estimate","ci_low","ci_high","lower_bound","upper_bound","unit","justification_source","source_status")];equivalence$assessment<-ifelse(equivalence$ci_low>=equivalence$lower_bound & equivalence$ci_high<=equivalence$upper_bound,"equivalent_within_declared_bound",ifelse(equivalence$ci_low>equivalence$upper_bound,"meaningfully_positive_beyond_bound",ifelse(equivalence$ci_high<equivalence$lower_bound,"meaningfully_negative_beyond_bound","inconclusive")));equivalence$nonsignificance_implies_equivalence<-FALSE;equivalence$data_status<-STATUS_CH19
 risk<-list();set.seed(19042026)
 for(i in seq_len(nrow(scenarios))){s<-scenarios[i,];se<-results$standard_error[match(s$contrast_id,results$contrast_id)];draws<-stats::rnorm(as.integer(s$simulation_replicates),as.numeric(s$true_effect_scenario),se);selected<-abs(draws/se)>1.96;sel<-draws[selected];type_s<-if(length(sel))mean(sign(sel)!=sign(as.numeric(s$true_effect_scenario))) else NA_real_;type_m<-if(length(sel))mean(abs(sel)/abs(as.numeric(s$true_effect_scenario))) else NA_real_;risk[[i]]<-data.frame(scenario_id=s$scenario_id,contrast_id=s$contrast_id,true_effect_scenario=as.numeric(s$true_effect_scenario),standard_error_from_design=se,selection_probability=mean(selected),type_s_risk=type_s,type_m_factor=type_m,selected_simulations=length(sel),simulation_replicates=as.integer(s$simulation_replicates),scenario_source=s$scenario_source,source_status=s$source_status,observed_estimate_used_as_truth=FALSE,data_status=STATUS_CH19)}
 risk<-do.call(rbind,risk);dir.create(output_dir,recursive=TRUE,showWarnings=FALSE);write_tsv_ch19(joined,file.path(output_dir,"research_scale_results.tsv"));write_tsv_ch19(bounds,file.path(output_dir,"meaningful_bounds.tsv"));write_tsv_ch19(equivalence,file.path(output_dir,"equivalence_assessment.tsv"));write_tsv_ch19(risk,file.path(output_dir,"sign_magnitude_risk.tsv"));report<-paste0("<!doctype html><meta charset='utf-8'><title>Interpretation diagnostics</title><h1>Research-scale interpretation</h1><p><strong>Data status:</strong> SYNTHETIC_TEACHING_FIXTURE. Bounds and true-effect scenarios are generator specifications, not empirical thresholds or observed truth.</p><h2>Equivalence</h2>",html_table_ch19(equivalence),"<h2>Type S and Type M design scenarios</h2>",html_table_ch19(risk));writeLines(report,file.path(output_dir,"interpretation_diagnostics.html"),useBytes=TRUE)
 decisions<-list(direction_magnitude_precision_separated=TRUE,threshold_generated_claims=FALSE,inconclusive_retained=any(equivalence$assessment=="inconclusive"),observed_estimate_used_as_scenario_truth=FALSE,bounds_empirically_validated=FALSE,scope_decision=scope$decision,sensitivity_outcome=sensitivity$result_universe_outcome,significance_vote_permitted=FALSE);write_provenance_ch19(file.path(output_dir,"run_provenance.json"),"run_results_uncertainty",c(results_path,scope_gate_path,map_path,bounds_path,scenario_path,sensitivity_path),decisions);list(results=joined,equivalence=equivalence,risk=risk,decisions=decisions)
}
run_claim_evidence_map<-function(map_path,draft_path,evidence_path,result_path,regression_gate_path,corpus_gate_path,model_scope_path,sensitivity_path,output_dir){
 map<-yaml::read_yaml(map_path);claims<-read_tsv_ch19(draft_path);evidence<-read_tsv_ch19(evidence_path);results<-read_tsv_ch19(result_path);regression<-yaml::read_yaml(regression_gate_path);corpus<-yaml::read_yaml(corpus_gate_path);scope<-yaml::read_yaml(model_scope_path);sensitivity<-yaml::read_yaml(sensitivity_path)
 if(!all(c(map$data_status,claims$data_status,evidence$data_status,results$data_status,regression$data_status,corpus$data_status,scope$data_status,sensitivity$data_status)==STATUS_CH19))stop("Chapter 19 claim inputs must remain explicitly synthetic")
 support<-list();unsupported<-list();domains<-list();registry<-claims
 for(i in seq_len(nrow(claims))){c<-claims[i,];reasons<-character();support_ids<-character();result_available<-c$result_id%in%results$contrast_id || c$result_id=="CH18_SELECTED_MODEL";if(result_available)support_ids<-c(support_ids,if(c$result_id=="CH18_SELECTED_MODEL")"E_SCOPE_CH18" else "E_RESULT_CH17") else reasons<-c(reasons,"declared result is unavailable")
  if(c$requires_new_items=="true" && identical(regression$new_unit_scope$items,FALSE))reasons<-c(reasons,"new-item generalization is prohibited by the fitted item scope")
  if(c$requires_causal_identification=="true")reasons<-c(reasons,"no causal identification or mechanism-discrimination evidence is supplied")
  if(c$requires_external_corpus=="true" && identical(scope$external_corpus_validation,FALSE))reasons<-c(reasons,"external-corpus validation is absent")
  if(c$evidence_level=="prediction")support_ids<-c(support_ids,"E_SCOPE_CH18");if(c$evidence_level=="association")support_ids<-c(support_ids,"E_MODEL_CH17","E_SENS_CH14")
  status<-if(length(reasons))"fail" else "qualify_human_review";registry$gate_status[i]<-status;registry$calibrated_wording[i]<-"HUMAN_SCIENTIFIC_JUDGMENT_REQUIRED";registry$required_revision_action[i]<-if(length(reasons))paste(reasons,collapse=" | ") else "retain synthetic status, observed-item scope, uncertainty, and diagnostics in wording"
  support[[i]]<-data.frame(claim_id=c$claim_id,result_available=result_available,evidence_ids=paste(unique(support_ids),collapse="|"),regression_gate=regression$decision,corpus_gate=corpus$decision,model_scope_gate=scope$decision,sensitivity_outcome=sensitivity$result_universe_outcome,human_approval_required=TRUE,data_status=STATUS_CH19)
  if(length(reasons))for(reason in reasons)unsupported[[length(unsupported)+1]]<-data.frame(claim_id=c$claim_id,unsupported_clause=c$proposed_text,reason=reason,required_action="remove, narrow, or supply independent evidence",remains_visible=TRUE,data_status=STATUS_CH19)
  domains[[i]]<-data.frame(claim_id=c$claim_id,population_scope=c$population_reach,item_scope=c$item_reach,measurement_scope=scope$measurement_scope,predictor_scope=scope$predictor_scope,goal_scope=c$goal_reach,absent_domains=paste(c(corpus$unsupported_claims,if(scope$external_corpus_validation)character() else "external corpora"),collapse=" | "),data_status=STATUS_CH19)
 }
 support<-do.call(rbind,support);unsupported<-if(length(unsupported))do.call(rbind,unsupported) else data.frame(claim_id=character(),unsupported_clause=character(),reason=character(),required_action=character(),remains_visible=logical(),data_status=character());domains<-do.call(rbind,domains);gate<-list(data_status=STATUS_CH19,decision="require_revision_and_human_approval",claims_total=nrow(registry),claims_failed=sum(registry$gate_status=="fail"),claims_qualified=sum(registry$gate_status=="qualify_human_review"),automatic_claim_generation=FALSE,threshold_generated_claims=FALSE,causal_claim_approved=FALSE,new_item_generalization_approved=FALSE,external_corpus_generalization_approved=FALSE,negative_and_unsupported_evidence_retained=TRUE,final_wording_approved=FALSE)
 dir.create(output_dir,recursive=TRUE,showWarnings=FALSE);write_tsv_ch19(registry,file.path(output_dir,"claim_registry.tsv"));write_tsv_ch19(support,file.path(output_dir,"claim_support.tsv"));write_tsv_ch19(unsupported,file.path(output_dir,"unsupported_clauses.tsv"));write_tsv_ch19(domains,file.path(output_dir,"domain_statements.tsv"));yaml::write_yaml(gate,file.path(output_dir,"calibrated_claim_gate.yaml"));decisions<-list(gate=gate,claim_order=registry$claim_id,evidence_inventory=evidence$evidence_id,human_scientific_judgment_required=TRUE);write_provenance_ch19(file.path(output_dir,"run_provenance.json"),"run_claim_evidence_map",c(map_path,draft_path,evidence_path,result_path,regression_gate_path,corpus_gate_path,model_scope_path,sensitivity_path),decisions);list(registry=registry,support=support,unsupported=unsupported,domains=domains,gate=gate)
}
